---

- hosts: backends
  remote_user: root
  vars_files:
    - "config/vars.yml"

  tasks:
    - name: Dump local DB
      local_action: shell pg_dump {{ local_db_name }} > ../tmp/{{ db_name }}.sql
      become: yes
      become_user: '{{ user }}'

    - name: upload db
      fetch: flat=true src=/home/{{ user }}/{{ db_name }}.sql dest=/tmp
      copy: src="../tmp/{{ db_name }}.sql" dest="/home/{{ user }}/{{ db_name }}.sql"
      become: yes
      become_user: '{{ user }}'


    - shell: dropdb {{ db_name }}
      ignore_errors: yes

    - name: rails prepare - create role
      postgresql_user: name={{ user }} password={{ db_pass }} role_attr_flags=CREATEDB,SUPERUSER

    - name: Create database on localhost
      shell: createdb -T template0 {{ db_name }}

    - name: Restore DB dump on localhost
      local_action: shell psql -1 -d {{ db_name }} < /tmp/{{ db_name }}.sql
