---

- hosts: postgres
  remote_user: root
  vars_files:
    - "config/vars.yml"

  tasks:
    - name: Dump local DB
      local_action: shell pg_dump {{ db_name }} > /tmp/{{ db_name }}.sql


    - name: upload db to serv
      copy: src="/tmp/{{ db_name }}.sql" dest="/home/{{ user }}/{{ db_name }}.sql"
      become: yes
      become_user: '{{ user }}'

    - name: kill processes connected to db!
      shell: echo "DROP DATABASE {{ db_name }};"
      become: yes
      become_user: '{{ user }}'

    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
      sudo: true

    - shell: dropdb {{ db_name }}
      become: yes
      become_user: '{{ user }}'
      ignore_errors: yes

    - name: rails prepare - create role
      postgresql_user: name={{ user }} password={{ db_pass }} role_attr_flags=CREATEDB,SUPERUSER

    - name: Create database on localhost
      shell: createdb -T template0 {{ db_name }}
      become: yes
      become_user: '{{ user }}'

    - name: Restore DB dump on remote server
      shell: psql -d {{ db_name }} < /home/{{ user }}/{{ db_name }}.sql
      become: yes
      become_user: '{{ user }}'