- hosts: locals
  remote_user: '{{ user }}'
  vars_files:
    - "config/localhost_vars.yml"

  tasks:
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
      become_user: root
      become: true

    - name: db drop
      shell: rake db:drop

    - shell: rake db:setup

    - name: db:create
      shell: rake db:create



    - name: import database
      shell: psql -d --single-transaction -v ON_ERROR_STOP=1 {{ db_name }} -f /tmp/{{ db_name }}.sql
      become: true
      become_user: postgres

    - shell: rake db:migrate
      ignore_errors: true

    - shell: rake db:migrate