---
- hosts: backends
  remote_user: root
  vars:
    - include_vars: vars.yml

  pre_tasks:
    - name: Local - git add, commit, push
      local_action: shell cd .. && git add ./* && git commit -m '{{ commit|default("none") }}' && git push origin {{ branch }}
      tags: ['commit', 'deploy']

  roles:
    - { role: common, tags: ["setup"] }
    #- backends
    #- { role: rvm_io.rvm1-ruby, rvm1_rubies: ["ruby-2.3.1"], tags: ["rvm", "setup"] }


    #- role: zzet.postgresql
    #  pg_version: 9.4
    #  pg_postgis: true
    - { role: postgresql, when: not skip_pg, tags: ["postgresql", "setup"] }

    - { role: sbaerlocher.redis, when: not skip_redis, tags: ["redis", "setup"] }

    - { role: rvm, tags: ["rvm", "setup"] }
    - { role: rails }