---

- name: rails prepare - copy ssh private key
  copy: 'src=../../../config/id_rsa dest={{ home }}/.ssh/id_rsa mode=0600'
  become: yes
  become_user: '{{ user }}'


- name: rails prepare - copy ssh public key
  copy: 'src=../../../config/id_rsa.pub dest={{ home }}/.ssh/id_rsa.pub mode=0644'
  become: yes
  become_user: '{{ user }}'
