---

- name: create static dirs in shared folder
  file:
    dest: "{{ rails_path_app }}/shared/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    recurse: yes
    state: directory
  with_items: "{{ static_dirs }}"

- name: remove static dirs from release sources
  file: dest="{{ rails_release_path }}/{{ item }}" owner="{{ user }}" group="{{ user }}" state=absent
  with_items: "{{ static_dirs }}"
  ignore_errors: yes

- name: link static dirs from shared
  file: src="{{ rails_path_app }}/shared/{{ item }}" dest="{{ rails_release_path }}/{{ item }}" owner="{{ user }}" group="{{ user }}" state=link
  with_items: "{{ static_dirs }}"