---

- name: webpack - get local node version
  local_action: command cat ../.node-version
  register: node_ver

- name: webpack - compile
  #local_action: shell bash --login -c 'cd .. && NODE_ENV=production nvm exec {{ node_ver.stdout }} webpack -p --config {{ webpack_entry }}'
  local_action: shell bash --login -c 'cd .. && NODE_ENV=production nvm exec {{ node_ver.stdout }} npm run build'
  when: webpack_production

- name: webpack - compile
  local_action: shell bash --login -c 'cd .. && NODE_ENV=development nvm exec {{ node_ver.stdout }} npm run build'
  when: not webpack_production

- name: webpack - remove remote public
  file: path='{{ rails_path_app }}/shared/public/*' state=absent

- name: webpack - rsync upload public
  synchronize: src="../public/" dest="{{ rails_path_app }}/shared/public/" delete=yes recursive=yes
  become: yes
  become_user: '{{ user }}'

