---

- name: Create unicorn config directory
  file: dest=/etc/unicorn state=directory owner=root group=root mode=0755
  when: app_dirs_created|changed

- name: Create unicorn config
  template: src=unicorn-app.j2 dest=/etc/unicorn/{{ app_name }}.conf owner=root group=root mode=0644

- name: Create unicorn.rb
  template: src=unicorn_rb.j2 dest={{ rails_path_app }}/shared/config/unicorn/unicorn.rb owner={{ user }} group={{ user }}
  become_user: "{{ user }}"
  become: yes

- name: Install unicorn systemd service
  template: src=unicorn.service.j2 dest=/etc/systemd/system/unicorn-{{ app_name }}.service owner=root group=root mode=0755
  when: app_dirs_created|changed

- name: Enable unicorn service
  systemd: name=unicorn-{{ app_name }} enabled=yes
  when: app_dirs_created|changed

- name: Nginx write app config
  template: src={{ config_nginx_appconf }} dest=/etc/nginx/sites-available/{{ app_name }}.conf group=www-data owner=www-data force=yes

- name: Nginx | Enable apps
  file: path=/etc/nginx/sites-enabled/{{ app_name }}.conf src=/etc/nginx/sites-available/{{ app_name }}.conf state=link
  ignore_errors: yes
