---
- include: 'local.yml'

- include: 'create_dirs.yml'

- include: 'install_services.yml'

- include: 'upload.yml'

- include: 'link_shared.yml'

- name: Detect rvm binary
  stat: path='{{ rvm_bin }}'
  register: rvm_binary

- include: 'rvm.yml'
  when: not (rvm_binary.stat is defined and rvm_binary.stat.exists)

- include: 'ruby.yml'

- include: 'rails.yml'
  when: not (config_mongodb)

- include: 'mongodb.yml'
  when: config_mongodb

- include: 'crontab.yml'

- include: 'upload_wp_build.yml'

- include: 'release.yml'