---

- name: Write database.yml
  template: src=mongoid.yml.j2 dest={{ rails_release_path }}/config/mongoid.yml owner={{ user }} group={{ user }}

- name: Write secrets.yml
  template: src=secrets.yml.j2 dest={{ rails_release_path }}/config/secrets.yml owner={{ user }} group={{ user }}

- name: Precompile assets
  command: '{{ gem_bins_path }}/bundle exec rake assets:precompile'
  environment:
    RAILS_ENV: '{{ rails_env }}'
  args:
    chdir: '{{ rails_release_path }}'
  become: yes
  become_user: '{{ user }}'
  async: 600
  poll: 0
  register: assets_precompile_wait
  when: config_precompile_assets