---

ruby: 'ruby-2.3.1'

# Install path for rvm
rvm_install_path: '{{ home }}/.rvm'

# Add or remove any install flags
# NOTE: If you are doing a USER BASED INSTALL then
#       make sure you ADD the --user-install flag below
rvm_install_flags: '--auto-dotfiles --user-install'

ruby_install flags:

# Set the owner for the rvm directory
rvm_user: "{{ user }}"

# URL for the latest installer script
rvm_latest_installer: 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer'


# GPG key verification, use an empty string if you want to skip this
# Note: Unless you know what you're doing, just keep it as is
#           Identity proof: https://keybase.io/mpapis
#           PGP message: https://rvm.io/mpapis.asc
rvm_gpg_keys: 'D39DC0E3'

# The GPG key server
rvm_gpg_key_server: 'hkp://keys.gnupg.net'

# autolib mode, see https://rvm.io/rvm/autolibs
rvm_autolib_mode: 0
