---
- block:
  - name: Detect  installed rubies and gemsets
    command: '{{ rvm_bin }} list gemsets'
    register: detect_gemsets
    ignore_errors: true

  - name: Install rubies
    command: '{{ rvm_bin }} install {{ ruby }} {{ ruby_install_flags }}'
    when: "'{{ ruby }}' not in detect_gemsets.stdout"

  - name: Select gemset, create .ruby-version .ruby-gemset
    command: '{{ rvm_bin }} --create --ruby-version {{ gemset }}'
    when: "'{{ gemset }}' not in detect_gemsets.stdout"
    chdir: "{{ rails_release_path }}"

  - name: Install bundler if not installed
    command: "{{ gem_bins_path }}/gem install bundler"

become: yes
become_user: '{{ rvm_user }}'